server:
  port: 8181

spring:
  application:
    name: auth-gateway
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://keycloak.cantalay.com/realms/master
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: gateway-client
            client-secret: lNNGQ7iNWhTkLWELRpwkSmYwA0xGdfx5
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.cantalay.com/realms/master
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: example-route
              uri: http://httpbin.org
              predicates:
                - Path=/get
      default-filters:
        - AddRequestHeader=X-Correlation-Id, ${random.uuid}
      routes:
        # Token alma
        - id: keycloak-token
          uri: https://keycloak.cantalay.com
          predicates:
            - Path=/token
          filters:
            - RewritePath=/token, /realms/master/protocol/openid-connect/token

        # Refresh token
        - id: keycloak-refresh
          uri: https://keycloak.cantalay.com
          predicates:
            - Path=/refresh
          filters:
            - RewritePath=/refresh, /realms/master/protocol/openid-connect/token

        # Kullanıcı bilgisi
        - id: keycloak-userinfo
          uri: https://keycloak.cantalay.com
          predicates:
            - Path=/userinfo
          filters:
            - RewritePath=/userinfo, /realms/master/protocol/openid-connect/userinfo

        # Yetkilendirme
        - id: keycloak-authorize
          uri: https://keycloak.cantalay.com
          predicates:
            - Path=/authorize
          filters:
            - RewritePath=/authorize, /realms/master/protocol/openid-connect/auth

        # Logout
        - id: keycloak-logout
          uri: https://keycloak.cantalay.com
          predicates:
            - Path=/logout
          filters:
            - RewritePath=/logout, /realms/master/protocol/openid-connect/logout

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus  # sadece gerekli endpointler
  endpoint:
    prometheus:
      access: UNRESTRICTED
  metrics:
    tags:
      application: ${spring.application.name}

